name: copdbuddy
description: An app for doctors to keep track of patients
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core:
  firebase_auth:
  flutter_svg:
  cloud_firestore:
  firebase_storage:
  uuid:
  url_launcher:
  flutter_local_notifications:
  intl:
  timezone:
  fl_chart:
  excel: ^2.0.5
  path_provider: ^2.0.15
  open_file: ^3.0.1
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_app_name:

  flutter_lints: ^2.0.0
flutter_app_name:
  name: "Breathe Buddy"

flutter:

  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Poppins
       fonts:
         - asset: fonts/Poppins-SemiBold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
     - family: Nunito
       fonts:
         - asset: fonts/Nunito-VariableFont_wght.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
