// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtPTKkkKWCaNkdCBKgFxzLk4Aoa1KQql0',
    appId: '1:148934821829:web:594b537abee590e118adac',
    messagingSenderId: '148934821829',
    projectId: 'copdbuddy',
    authDomain: 'copdbuddy.firebaseapp.com',
    storageBucket: 'copdbuddy.appspot.com',
    measurementId: 'G-RDFYYBGE7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUx4RXS6qlzxQeLzA6TM54LKS0Vih3-k0',
    appId: '1:148934821829:android:2017cf9ab00e5aea18adac',
    messagingSenderId: '148934821829',
    projectId: 'copdbuddy',
    storageBucket: 'copdbuddy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhflR584DUk_ywyWleW1HLW-SgHHhFUrA',
    appId: '1:148934821829:ios:c11dc8da61865a2d18adac',
    messagingSenderId: '148934821829',
    projectId: 'copdbuddy',
    storageBucket: 'copdbuddy.appspot.com',
    iosBundleId: 'com.example.copdbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhflR584DUk_ywyWleW1HLW-SgHHhFUrA',
    appId: '1:148934821829:ios:428b0fc13ba147eb18adac',
    messagingSenderId: '148934821829',
    projectId: 'copdbuddy',
    storageBucket: 'copdbuddy.appspot.com',
    iosBundleId: 'com.example.copdbuddy.RunnerTests',
  );
}
